### ISSUE TITLE
Missing DirectorySeperatorChar in ModLoader.cs

### ISSUE THREAD

**Issue by MisterKudo** [TekkaGB/PizzaOven#1]
At precisely line 118 of ModLoader.cs, there is a missing DirectorySeperatorChar right before _"sound"_:

`var FileToReplace = $"{Global.config.ModsFolder}sound{Global.s}Desktop{Global.s}{Path.GetFileName(modFile)}";`

This causes Pizza Oven to look for sound files in _"Pizza Towersound/"..._ instead of _"Pizza Tower/sound/"..._ causing it to fail loading mods with sound files in them.

Here is the fixed version:

`var FileToReplace = $"{Global.config.ModsFolder}{Global.s}sound{Global.s}Desktop{Global.s}{Path.GetFileName(modFile)}";
`

**Comment by TekkaGB** [comment]
Thanks for letting me know. I’ll fix it as soon as I have access to my computer again

**Comment by Dsboiboi** [comment]
I've all up in pizza oven files and the files here but i cant figure out anything, i still cant figure out how to fix the problem since the pizza oven download doesnt have moddownloader.cs, and no matter how much i move around nothing works?

**Comment by TekkaGB** [comment]
Sorry for the inconvenience, I'm on vacation and don't return back to my computer until Saturday to fix this simple issue

**Comment by MisterKudo** [comment]
It seems like you are confused, @Dsboiboi. ModLoader.cs is a file in the source code, not the release. This means you would have to compile the code with the error fixed, which would require certain programs to do so. 
Basically, messing with your current install of Pizza Oven won't fix the issue, you'd need to mess with the source code, which is a lot trickier to work with for most.

**Comment by MisterKudo** [comment]
Also, that's unfortunate timing, @TekkaGB. But I hope you did have a nice vacation.

**Comment by TekkaGB** [comment]
Finally fixed
