### ISSUE TITLE
ISSUE : "Updated/Added" Date breaks at page 73.

### ISSUE THREAD

**Issue by mxlouka** [TekkaGB/PizzaOven#13]
So basically, since we have a **huge amount of mods now in the gamebanana** page, but i don't think **Pizza Oven can only handle so many pages**. When it tries to display the date **at page 73 and beyond, it breaks completely and instead says that it was updated/added 53 YEARS AGO**. So yeah, that's pretty much it. But this could maybe get worse in the future and become a real issue if this isn't fixed. Here's a screenshot : 
![image](https://github.com/TekkaGB/PizzaOven/assets/95552336/91a4274d-7e0f-4736-b1e9-41bee3333244)

**Comment by TekkaGB** [comment]
Fixed in https://github.com/TekkaGB/PizzaOven/commit/07a5c287a0670cc159ac9d127e41f8c7361a2321 It's a weird bug with GameBanana API returning 0 for the date updated
