### ISSUE TITLE
help me pizza oven wont let me browse mods

### ISSUE THREAD

**Issue by NathanInGithUB** [TekkaGB/PizzaOven#14]
for some reason i cant browse mods anymore because pizza oven tells me the json value cant be converted to system to system.uri

path: $[2]._aAlternateFileSources[0].url

LineNumber: 375

BytePositionLine: 46.

if you have any idea how to fix this COMMENT NOW PLEASE!

**Comment by TekkaGB** [comment]
Fixed in https://github.com/TekkaGB/PizzaOven/releases/tag/1.0.8
