### ISSUE TITLE
I get a trojan every time I download the zip from gamebanana.

### ISSUE THREAD

**Issue by Lumi1323** [TekkaGB/PizzaOven#34]
I'm given a trojan every time. Here is a picture.
![Screenshot 2023-12-12 191947](https://github.com/TekkaGB/PizzaOven/assets/111160282/715fa232-213d-4377-8652-a070cb09fe5a)
![Screenshot 2023-12-12 192138](https://github.com/TekkaGB/PizzaOven/assets/111160282/a3f27485-39a2-4afd-9d52-b54d3e8f0f48)
Care to explain?

**Comment by Lumi1323** [comment]
wait its my computer nvm

**Comment by Lumi1323** [comment]
It's from the latest update. Your latest update has a trojan known as Bearfoos apparently. I went back an update and it allows download.

**Comment by birddaughter** [comment]
Bearfoos.A!ml is a very common detection by Windows Defender, to a point where it is often a false positive. 

While there _is_ the possibility of there being a trojan in Pizza Oven, this kind of detection is most often found on freshly-compiled executables.

The project maintainer should report this false positive to Microsoft so it can be resolved.

**Comment by lumithespoofy64** [comment]
This is no longer relevant.
