### ISSUE TITLE
just does not work

### ISSUE THREAD

**Issue by pizzatowerman2** [TekkaGB/PizzaOven#6]
"Create Your Own Pizza (NEW level editor)\ownpizza_beta2-1.xdelta wasn't able to patch any file. Ensure that either the mod xdelta patch or your game version is up to date" Keeps popping up whenever I load a mod into pizza oven and try to launch it. I have redownloaded the mod, pizza tower, and xdelta multiple times but it just does not work, I also have set up pizza oven.

**Comment by TekkaGB** [comment]
Try validating steam files. Everything is still working on my end

**Comment by pizzatowerman2** [comment]
Tried it multiple times, and it finally worked! Thanks man, now I can actually play mods.
